### ISSUE TITLE
blog post series?

### ISSUE THREAD

**Issue by lygaret** [AndreaOrru/zen#36]
I've been following along with this project sort of commit by commit, and it's been a fantastic way of digging into Zig, as well as reenforcing things I've learned doing other small kernel experiments.

I was wondering if you'd be alright with me basing a series of blog posts on following along with this repo, sort of in the vein of [Writing an OS in Rust by Philipp Oppermann](https://os.phil-opp.com) (though almost guaranteed not as popular ;)).

I don't want to jump on the work you've done without asking your blessing, so let me know if you have concerns!

Thanks!
- Jon

**Comment by AndreaOrru** [comment]
Hi Jon!

Really happy you like Zen and glad it's been useful to you! I've actually been thinking about writing a blog post series based on it myself - I think it's a great idea.

As long as the blogposts point at the original project, you have my blessing of course. :) Let me know if I can help in any way by brainstorming, reviewing the material, improving the codebase, etc.

Also, contributions and design input are more than welcome!

**Comment by lygaret** [comment]
Awesome, thanks! I'll keep you up to date - this is sort of an experiment for me, but I'm excited about it :sweat_smile:
