### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by callowaysutton** [AndreaOrru/zen#38]
I got the following error when I tried to build the source.
```
build.zig:23:40: error: expected token 'Symbol', found '{'
    const common_params = [][]const u8.{
                                       ^
```

Anyone know what the problem could be?
Running Windows 10 Pro 64 bit, i3 7100T

**Comment by andrewrk** [comment]
It's not updated to the latest master branch of zig

**Comment by callowaysutton** [comment]
I've tried building with every release of Zig so far and all of them provided that error or an error close to that manner

**Comment by AndreaOrru** [comment]
Thanks @andrewrk!
